language: julia

os:
  - osx
  - linux

julia:
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - nightly

branches:
  only:
    - master

matrix:
  allow_failures:
    - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("HarwellRutherfordBoeing"); Pkg.test("HarwellRutherfordBoeing"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("HarwellRutherfordBoeing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

