language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

branches:
  only:
    - master

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("HarwellRutherfordBoeing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
